version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: examen
      MYSQL_USER: examuser
      MYSQL_PASSWORD: exam123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build: .
    image: maruan3/examen-academico:latest
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: examuser
      DB_PASSWORD: exam123
      DB_NAME: examen
      SECRET_KEY: super-secret-change-me
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 20 --label-enable --cleanup

volumes:
  db_data:
